import Head from 'next/head'
import { useRouter } from 'next/router'
import withAuth from '../components/hoc/withAuth'
import { useAppDispatch } from '../hooks'
import { IPrivateComponent } from '../interfaces/private-component.interface'
import { removeUser } from '../store/auth/auth.slice'
import { useListPlaylistsQuery } from '../store/playlists/playlists.api'
import { Playlist, Track } from '../store/playlists/playlists.types'
import styles from '../styles/Home.module.css'
import { NextPageWithLayout } from './_app'

const Home: NextPageWithLayout<IPrivateComponent> = ({ user }) => {
  const router = useRouter()
  const dispatch = useAppDispatch()

  const { isLoading, isError, data } = useListPlaylistsQuery(null)

  const logoutUser = () => {
    dispatch(removeUser())
    localStorage.removeItem('token')
    router.push('/login')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-2xl font-bold">
          Welcome, { user.firstName }
        </h1>

        <div>Your playlists:</div>
        {
          isLoading ? <div>Loading...</div> : (
            <div className='flex w-full'>
              {
                data?.items.map((playlist: Playlist) => (
                  <div className='mr-3' key={playlist.id}>
                    <div>Name: { playlist.name } </div>
                    <div>Tracks: </div>
                    {
                      playlist.tracks.map((track: Track) => (
                        <div className='m-1 p-1 border border-solid border-black rounded-sm' key={track._id}>
                          <div>Title: { track.title }</div>
                          <div>URL: <a href={ track.url } target="blank" className='text-blue-400 underline pointer'>Go</a></div>
                          <div>Artist: { track.artist || '' }</div>
                          <div>Album: { track.album || '' }</div>
                        </div>
                      ))
                    }
                  </div>
                ))
                }
            </div>
          )
        }
      </main>
    </div>
  )
}

export default withAuth(Home)
